import type { Deal, DealCategory, FilterCategory } from './types';

export const filterCategories: FilterCategory[] = ['All', 'Firearms', 'Accessories', 'Ammunition', 'Optics', 'Gear'];

export const placeholderDeals: Deal[] = [
  {
    id: '1',
    productName: 'Glock 19 Gen 5 Pistol',
    productDescription: 'The Glock 19 Gen 5 9mm pistol is ideal for a more versatile role due to its reduced dimensions. The new frame design without finger grooves still allows to instantly customize its grip to accommodate any hand size by mounting the different back straps. The reversible magazine catch and ambidextrous slide stop lever make it ideal for left and right-handed shooters.',
    category: 'Firearms',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'pistol handgun',
    retailer: 'Ammo Bros',
    retailerUrl: 'https://www.ammobros.com/shop/glock/glock-19-gen-5-9mm-pistol-4-02-barrel-15-rounds-122560',
    originalPrice: 599.99,
    dealPrice: 539.99,
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    tags: ['glock', 'pistol', '9mm', 'gen5', 'handgun'],
    popularityScore: 95,
    discountPercentage: Math.round(((599.99 - 539.99) / 599.99) * 100),
  },
  {
    id: '2',
    productName: 'Magpul PMAG 30 AR/M4 GEN M3 Magazine',
    productDescription: 'The PMAG 30 AR/M4 GEN M3 is a 30-round polymer magazine for AR15/M4 compatible weapons chambered in 5.56x45 NATO/.223 Remington. It features an impact resistant polymer construction, easy to disassemble design with a flared floorplate for positive magazine extraction, resilient stainless steel spring for corrosion resistance, and an anti-tilt, self-lubricating follower for increased reliability.',
    category: 'Accessories',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rifle magazine',
    retailer: 'Primary Arms',
    retailerUrl: '#',
    originalPrice: 14.95,
    dealPrice: 10.75,
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    tags: ['magpul', 'pmag', 'ar15', 'magazine', '556'],
    popularityScore: 88,
    discountPercentage: Math.round(((14.95 - 10.75) / 14.95) * 100),
  },
  {
    id: '3',
    productName: 'Federal American Eagle 5.56mm 55gr FMJBT Ammunition - 1000 Rounds',
    productDescription: 'Practice and train with reliable Federal American Eagle 5.56x45mm NATO ammunition. This 55 grain full metal jacket boat tail (FMJBT) ammo is perfect for target shooting, training, and plinking. Loaded to NATO specs.',
    category: 'Ammunition',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'ammo bullets',
    retailer: 'Palmetto State Armory',
    retailerUrl: '#',
    originalPrice: 499.99,
    dealPrice: 429.99,
    postedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), // 8 hours ago
    tags: ['federal', 'ammunition', '556', 'fmj', 'bulk'],
    popularityScore: 92,
    discountPercentage: Math.round(((499.99 - 429.99) / 499.99) * 100),
  },
  {
    id: '4',
    productName: 'Vortex Optics Strike Eagle 1-6x24 Riflescope',
    productDescription: 'The Strike Eagle 1-6x24 is defined by speed and versatility. A true 1x on the low end adapts to a wide range of scenarios, letting shooters rapidly engage targets from point-blank to extended ranges. The illuminated, glass-etched BDC3 reticle aids in rapid visual target acquisition.',
    category: 'Optics',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rifle scope',
    retailer: 'OpticsPlanet',
    retailerUrl: '#',
    originalPrice: 399.99,
    dealPrice: 299.99,
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    tags: ['vortex', 'scope', 'lpvo', 'optics', 'ar15'],
    popularityScore: 85,
    discountPercentage: Math.round(((399.99 - 299.99) / 399.99) * 100),
  },
   {
    id: '5',
    productName: 'Streamlight TLR-1 HL Weapon Light',
    productDescription: 'The Streamlight TLR-1 HL provides an 1000 lumen blast of light for maximum illumination while clearing a room or searching an alley. Its wide beam pattern lights up large areas so you can identify who or what is nearby.',
    category: 'Accessories',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'weapon light',
    retailer: 'Brownells',
    retailerUrl: '#',
    originalPrice: 175.00,
    dealPrice: 139.99,
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['streamlight', 'weapon light', 'tlr1', 'tactical'],
    popularityScore: 90,
    discountPercentage: Math.round(((175.00 - 139.99) / 175.00) * 100),
  },
  {
    id: '6',
    productName: 'Howard Leight Impact Sport Earmuff',
    productDescription: 'Howard Leight Impact Sport Earmuffs provide protection from hazardous noise while allowing you to hear conversations and range commands. Amplifies low-level sounds up to 4x. NRR 22dB.',
    category: 'Gear',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'hearing protection',
    retailer: 'Amazon',
    retailerUrl: '#',
    originalPrice: 59.99,
    dealPrice: 45.00,
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['hearing protection', 'earmuffs', 'range gear'],
    popularityScore: 78,
    discountPercentage: Math.round(((59.99 - 45.00) / 59.99) * 100),
  }
];
