// src/components/ui/badge.tsx
// This is a reusable Badge component, likely adapted from ShadCN UI.
// Badges are used for displaying small pieces of information, statuses, or tags.
// It uses class-variance-authority (cva) for different badge styles.

import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority" // For variant-driven class names.

import { cn } from "@/lib/utils" // Utility for merging Tailwind classes.

// --- Badge Variants Definition ---
// `cva` defines base styles and variants for the badge component.
// 🔍 These variants control the visual appearance of the badge (e.g., color, border).
const badgeVariants = cva(
  // Base classes applied to all badges.
  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      // `variant` defines the badge's style.
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground hover:bg-primary/80", // Primary style.
        secondary:
          "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80", // Secondary style.
        destructive:
          "border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80", // Destructive/error style.
        outline: "text-foreground", // Outline style.
      },
    },
    // Default variant if not specified.
    defaultVariants: {
      variant: "default",
    },
  }
)

// --- Badge Props Interface ---
/**
 * @interface BadgeProps
 * @description Extends standard HTML div attributes and adds `cva` variants.
 */
export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>, // Badges are typically divs.
    VariantProps<typeof badgeVariants> {}

// --- Badge Component ---
/**
 * @component Badge
 * @description A reusable badge component for displaying statuses, tags, or short pieces of information.
 * Supports different visual styles through variants.
 * This is a common UI element for categorization or highlighting.
 * @param {BadgeProps} props - Props for the Badge component.
 */
function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    // Apply Tailwind classes generated by `badgeVariants` and any custom `className`.
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  )
}

export { Badge, badgeVariants }
